enable-ip-hashing=false
redis-host=redis
#redis-password=password
mongo-url=mongodb://mongoadmin:secret@mongo:27017
images-path=./images
# webhooks.punishments=
# webhooks.reports=
# webhooks.notes=
# webhooks.debug=
